src/Entity/Naissance.php
<?php

namespace App\Entity;

use App\Repository\NaissanceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NaissanceRepository::class)]
class Naissance
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column]
    private ?bool $sexe = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_naissance = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu_naissance = null;

    #[ORM\ManyToOne(inversedBy: 'naissances')]
    private ?Utilisateurs $pere = null;

    #[ORM\ManyToOne(inversedBy: 'naissances')]
    private ?Utilisateurs $mere = null;

    #[ORM\ManyToOne(inversedBy: 'declaration_naissance')]
    private ?Utilisateurs $demandeur = null;

    #[ORM\ManyToOne(inversedBy: 'demande_acte')]
    private ?Utilisateurs $demadeur_acte = null;

    #[ORM\Column(length: 255, nullable:true)]
    private ?string $fichier_retour = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable:true)]
    private ?\DateTimeInterface $dateDemande = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateRetour = null;

    #[ORM\Column]
    private ?bool $confirmer = null;

    #[ORM\Column]
    private ?int $num_porte = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function isSexe(): ?bool
    {
        return $this->sexe;
    }

    public function setSexe(bool $sexe): static
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): static
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getLieuNaissance(): ?string
    {
        return $this->lieu_naissance;
    }

    public function setLieuNaissance(string $lieu_naissance): static
    {
        $this->lieu_naissance = $lieu_naissance;

        return $this;
    }

    public function getPere(): ?Utilisateurs
    {
        return $this->pere;
    }

    public function setPere(?Utilisateurs $pere): static
    {
        $this->pere = $pere;

        return $this;
    }

    public function getMere(): ?Utilisateurs
    {
        return $this->mere;
    }

    public function setMere(?Utilisateurs $mere): static
    {
        $this->mere = $mere;

        return $this;
    }

    public function getDemandeur(): ?Utilisateurs
    {
        return $this->demandeur;
    }

    public function setDemandeur(?Utilisateurs $demandeur): static
    {
        $this->demandeur = $demandeur;

        return $this;
    }

    public function getDemadeurActe(): ?Utilisateurs
    {
        return $this->demadeur_acte;
    }

    public function setDemadeurActe(?Utilisateurs $demadeur_acte): static
    {
        $this->demadeur_acte = $demadeur_acte;

        return $this;
    }

    public function getFichierRetour(): ?string
    {
        return $this->fichier_retour;
    }

    public function setFichierRetour(string $fichier_retour): static
    {
        $this->fichier_retour = $fichier_retour;

        return $this;
    }

    public function getDateDemande(): ?\DateTimeInterface
    {
        return $this->dateDemande;
    }

    public function setDateDemande(\DateTimeInterface $dateDemande): static
    {
        $this->dateDemande = $dateDemande;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->dateRetour;
    }

    public function setDateRetour(?\DateTimeInterface $dateRetour): static
    {
        $this->dateRetour = $dateRetour;

        return $this;
    }

    public function isConfirmer(): ?bool
    {
        return $this->confirmer;
    }

    public function setConfirmer(bool $confirmer): static
    {
        $this->confirmer = $confirmer;

        return $this;
    }

    public function getNumPorte(): ?int
    {
        return $this->num_porte;
    }

    public function setNumPorte(int $num_porte): static
    {
        $this->num_porte = $num_porte;

        return $this;
    }
}

src/Form/NaissanceType.php
<?php

namespace App\Form;

use App\Entity\Naissance;
use App\Entity\Utilisateurs;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NaissanceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('sexe')
            ->add('date_naissance', null, [
                'widget' => 'single_text',
            ])
            ->add('lieu_naissance')
            ->add('pere', EntityType::class, [
                'class' => Utilisateurs::class,
                'choice_label' => function (Utilisateurs $utilisateurs){
                    return $utilisateurs->getNom(). " " . $utilisateurs->getPrenom();
                },
            ])
            ->add('mere', EntityType::class, [
                'class' => Utilisateurs::class,
                'choice_label' => function (Utilisateurs $utilisateurs){
                    return $utilisateurs->getNom(). " " . $utilisateurs->getPrenom();
                },
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Naissance::class,
        ]);
    }
}

src/Controller/NaissanceController.php
<?php

namespace App\Controller;

use App\Entity\Naissance;
use App\Form\NaissanceType;
use App\Repository\NaissanceRepository;
use DateTimeInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;


#[Route('/naissance')]
class NaissanceController extends AbstractController
{
    #[Route('/', name: 'app_naissance_index', methods: ['GET'])]
    public function index(NaissanceRepository $naissanceRepository): Response
    {
        return $this->render('naissance/index.html.twig', [
            'naissances' => $naissanceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_naissance_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $naissance = new Naissance();
        $form = $this->createForm(NaissanceType::class, $naissance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $naissance->setConfirmer(false);
            $naissance->setDemandeur($this->getUser());
            $naissance->setNumPorte(24);
            $entityManager->persist($naissance);
            $entityManager->flush();

            return $this->redirectToRoute('app_recup_fichier', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('naissance/new.html.twig', [
            'naissance' => $naissance,
            'form' => $form,
        ]);
    }
    #[Route('/new/acte', name: 'app_naissance_acte_new', methods: ['GET', 'POST'])]
    public function newActe(Request $request, EntityManagerInterface $entityManager): Response
    {
        $naissance = new Naissance();
        $form = $this->createForm(NaissanceType::class, $naissance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $naissance->setConfirmer(false);
            $naissance->setDemadeurActe($this->getUser());
            $naissance->setNumPorte(24);
            $entityManager->persist($naissance);
            $entityManager->flush();

            return $this->redirectToRoute('app_recup_fichier', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('naissance/new.html.twig', [
            'naissance' => $naissance,
            'form' => $form,
        ]);
    }
    #[Route('/{id}', name: 'app_naissance_show', methods: ['GET'])]
    public function show(Naissance $naissance): Response
    {
        return $this->render('naissance/show.html.twig', [
            'naissance' => $naissance,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_naissance_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Naissance $naissance, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(NaissanceType::class, $naissance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_naissance_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('naissance/edit.html.twig', [
            'naissance' => $naissance,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_naissance_edit_employe', methods: ['GET', 'POST'])]
    public function editEmploye(Request $request, Naissance $naissance, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(NaissanceType::class, $naissance);
        $form->handleRequest($request);
        $form->remove('nom');
        $form->remove('prenom');
        $form->remove('sex');
        $form->remove('date_naissance');
        $form->remove('nom');
        $form->remove('lieu_naissance');
        $form->remove('pere');
        $form->remove('mere');
        $form->add('fichier_retour');
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_naissance_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('naissance/edit.html.twig', [
            'naissance' => $naissance,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_naissance_delete', methods: ['POST'])]
    public function delete(Request $request, Naissance $naissance, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$naissance->getId(), $request->request->get('_token'))) {
            $entityManager->remove($naissance);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_naissance_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/naissance/_delete_form.html.twig
<form method="post" action="{{ path('app_naissance_delete', {'id': naissance.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ naissance.id) }}">
    <button class="btn">Delete</button>
</form>

templates/naissance/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/naissance/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Naissance{% endblock %}

{% block body %}
    <h1>Edit Naissance</h1>

    {{ include('naissance/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_naissance_index') }}">back to list</a>

    {{ include('naissance/_delete_form.html.twig') }}
{% endblock %}

templates/naissance/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Naissance index{% endblock %}

{% block body %}
    <h1>Naissance index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Sexe</th>
                <th>Date_naissance</th>
                <th>Lieu_naissance</th>
                <th>Fichier_retour</th>
                <th>DateDemande</th>
                <th>DateRetour</th>
                <th>Confirmer</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for naissance in naissances %}
            <tr>
                <td>{{ naissance.id }}</td>
                <td>{{ naissance.nom }}</td>
                <td>{{ naissance.prenom }}</td>
                <td>{{ naissance.sexe ? 'Yes' : 'No' }}</td>
                <td>{{ naissance.dateNaissance ? naissance.dateNaissance|date('Y-m-d') : '' }}</td>
                <td>{{ naissance.lieuNaissance }}</td>
                <td>{{ naissance.fichierRetour }}</td>
                <td>{{ naissance.dateDemande ? naissance.dateDemande|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ naissance.dateRetour ? naissance.dateRetour|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ naissance.confirmer ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_naissance_show', {'id': naissance.id}) }}">show</a>
                    <a href="{{ path('app_naissance_edit', {'id': naissance.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_naissance_new') }}">Create new</a>
{% endblock %}

templates/naissance/new.html.twig
{% extends 'demande_user.html.twig' %}

{% block demande %}Declaration  de naissance{% endblock %}

{% block body %}

    {{ include('naissance/_form.html.twig') }}

{% endblock %}

templates/naissance/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Naissance{% endblock %}

{% block body %}
    <h1>Naissance</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ naissance.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ naissance.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ naissance.prenom }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ naissance.sexe ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ naissance.dateNaissance ? naissance.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Lieu_naissance</th>
                <td>{{ naissance.lieuNaissance }}</td>
            </tr>
            <tr>
                <th>Fichier_retour</th>
                <td>{{ naissance.fichierRetour }}</td>
            </tr>
            <tr>
                <th>DateDemande</th>
                <td>{{ naissance.dateDemande ? naissance.dateDemande|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>DateRetour</th>
                <td>{{ naissance.dateRetour ? naissance.dateRetour|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Confirmer</th>
                <td>{{ naissance.confirmer ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_naissance_index') }}">back to list</a>

    <a href="{{ path('app_naissance_edit', {'id': naissance.id}) }}">edit</a>

    {{ include('naissance/_delete_form.html.twig') }}
{% endblock %}