src/Entity/Porte.php
<?php

namespace App\Entity;

use App\Repository\PorteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PorteRepository::class)]
class Porte
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $numero_porte = null;

    #[ORM\OneToMany(targetEntity: Service::class, mappedBy: 'porte')]
    private Collection $services;

    #[ORM\OneToMany(targetEntity: Employes::class, mappedBy: 'porte')]
    private Collection $employes;

    #[ORM\OneToMany(targetEntity: Utilisateurs::class, mappedBy: 'porte')]
    private Collection $porteEmployes;

    public function __construct()
    {
        $this->services = new ArrayCollection();
        $this->employes = new ArrayCollection();
        $this->porteEmployes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroPorte(): ?string
    {
        return $this->numero_porte;
    }

    public function setNumeroPorte(string $numero_porte): static
    {
        $this->numero_porte = $numero_porte;

        return $this;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getServices(): Collection
    {
        return $this->services;
    }

    public function addService(Service $service): static
    {
        if (!$this->services->contains($service)) {
            $this->services->add($service);
            $service->setPorte($this);
        }

        return $this;
    }

    public function removeService(Service $service): static
    {
        if ($this->services->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getPorte() === $this) {
                $service->setPorte(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Employes>
     */
    public function getEmployes(): Collection
    {
        return $this->employes;
    }

    public function addEmploye(Employes $employe): static
    {
        if (!$this->employes->contains($employe)) {
            $this->employes->add($employe);
            $employe->setPorte($this);
        }

        return $this;
    }

    public function removeEmploye(Employes $employe): static
    {
        if ($this->employes->removeElement($employe)) {
            // set the owning side to null (unless already changed)
            if ($employe->getPorte() === $this) {
                $employe->setPorte(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Utilisateurs>
     */
    public function getPorteEmployes(): Collection
    {
        return $this->porteEmployes;
    }

    public function addPorteEmploye(Utilisateurs $porteEmploye): static
    {
        if (!$this->porteEmployes->contains($porteEmploye)) {
            $this->porteEmployes->add($porteEmploye);
            $porteEmploye->setPorte($this);
        }

        return $this;
    }

    public function removePorteEmploye(Utilisateurs $porteEmploye): static
    {
        if ($this->porteEmployes->removeElement($porteEmploye)) {
            // set the owning side to null (unless already changed)
            if ($porteEmploye->getPorte() === $this) {
                $porteEmploye->setPorte(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->numero_porte;
    }
}

src/Form/PorteType.php
<?php

namespace App\Form;

use App\Entity\Porte;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PorteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('numero_porte')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Porte::class,
        ]);
    }
}

src/Controller/PorteController.php
<?php

namespace App\Controller;

use App\Entity\Porte;
use App\Form\PorteType;
use App\Repository\PorteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/porte')]
class PorteController extends AbstractController
{
    #[Route('/', name: 'app_porte_index', methods: ['GET'])]
    public function index(PorteRepository $porteRepository): Response
    {
        return $this->render('porte/index.html.twig', [
            'portes' => $porteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_porte_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $porte = new Porte();
        $form = $this->createForm(PorteType::class, $porte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($porte);
            $entityManager->flush();

            return $this->redirectToRoute('app_porte_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('porte/new.html.twig', [
            'porte' => $porte,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_porte_show', methods: ['GET'])]
    public function show(Porte $porte): Response
    {
        return $this->render('porte/show.html.twig', [
            'porte' => $porte,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_porte_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Porte $porte, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PorteType::class, $porte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_porte_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('porte/edit.html.twig', [
            'porte' => $porte,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_porte_delete', methods: ['POST'])]
    public function delete(Request $request, Porte $porte, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$porte->getId(), $request->request->get('_token'))) {
            $entityManager->remove($porte);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_porte_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/porte/_delete_form.html.twig
<form method="post" action="{{ path('app_porte_delete', {'id': porte.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ porte.id) }}">
    <button class="btn">Delete</button>
</form>

templates/porte/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/porte/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Porte{% endblock %}

{% block body %}
    <h1>Edit Porte</h1>

    {{ include('porte/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_porte_index') }}">back to list</a>

    {{ include('porte/_delete_form.html.twig') }}
{% endblock %}

templates/porte/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Porte index{% endblock %}

{% block body %}
    <h1>Porte index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Numero_porte</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for porte in portes %}
            <tr>
                <td>{{ porte.id }}</td>
                <td>{{ porte.numeroPorte }}</td>
                <td>
                    <a href="{{ path('app_porte_show', {'id': porte.id}) }}">show</a>
                    <a href="{{ path('app_porte_edit', {'id': porte.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_porte_new') }}">Create new</a>
{% endblock %}

templates/porte/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Porte{% endblock %}

{% block body %}
    <h1>Create new Porte</h1>

    {{ include('porte/_form.html.twig') }}

    <a href="{{ path('app_porte_index') }}">back to list</a>
{% endblock %}

templates/porte/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Porte{% endblock %}

{% block body %}
    <h1>Porte</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ porte.id }}</td>
            </tr>
            <tr>
                <th>Numero_porte</th>
                <td>{{ porte.numeroPorte }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_porte_index') }}">back to list</a>

    <a href="{{ path('app_porte_edit', {'id': porte.id}) }}">edit</a>

    {{ include('porte/_delete_form.html.twig') }}
{% endblock %}