src/Entity/Utilisateurs.php
<?php

namespace App\Entity;

use App\Repository\UtilisateursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UtilisateursRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_C_I_N', fields: ['CIN'])]
class Utilisateurs implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $CIN = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_naissance = null;

    #[ORM\Column]
    private ?int $age = null;

    #[ORM\Column]
    private ?bool $sexe = null;

    #[ORM\Column]
    private ?bool $status_matrimoniale = null;

    #[ORM\Column]
    private ?bool $vivant = null;

    #[ORM\Column]
    private ?int $profession = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu_naissance = null;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'pere')]
    private ?self $pere = null;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'mere')]
    private ?self $mere = null;

    #[ORM\OneToOne(targetEntity: self::class, cascade: ['persist', 'remove'])]
    private ?self $partenaire = null;

    #[ORM\OneToMany(targetEntity: Naissance::class, mappedBy: 'pere')]
    private Collection $naissances;

    #[ORM\OneToMany(targetEntity: Mariage::class, mappedBy: 'demandeur')]
    private Collection $demande_mariage;

    #[ORM\OneToMany(targetEntity: Deces::class, mappedBy: 'demandeur')]
    private Collection $demande_dece;

    #[ORM\OneToMany(targetEntity: Naissance::class, mappedBy: 'demandeur')]
    private Collection $declaration_naissance;

    #[ORM\OneToMany(targetEntity: Naissance::class, mappedBy: 'demadeur_acte')]
    private Collection $demande_acte;

    #[ORM\OneToMany(targetEntity: CertificationLegalisation::class, mappedBy: 'demandeur')]
    private Collection $demande_certification_legalisation;

    #[ORM\OneToMany(targetEntity: Livret::class, mappedBy: 'demandeur')]
    private Collection $demandeLivret;

    #[ORM\ManyToOne(inversedBy: 'porteEmployes')]
    private ?Porte $porte = null;

    #[ORM\ManyToOne(inversedBy: 'professionEmployes')]
    private ?Profession $profession_employes = null;

    #[ORM\ManyToOne(inversedBy: 'utilisateurs')]
    private ?Quartier $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\OneToMany(targetEntity: Deces::class, mappedBy: 'demandeur_acte')]
    private Collection $demandeur_acte;

    public function __construct()
    {
        $this->demandeur_acte = new ArrayCollection();
    }

    /*public function __construct()
    {
        $this->pere = new ArrayCollection();
        $this->mere = new ArrayCollection();
        $this->naissances = new ArrayCollection();
        $this->demande_mariage = new ArrayCollection();
        $this->demande_dece = new ArrayCollection();
        $this->declaration_naissance = new ArrayCollection();
        $this->demande_acte = new ArrayCollection();
        $this->demande_certification_legalisation = new ArrayCollection();
        $this->demandeLivret = new ArrayCollection();
    }*/

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCIN(): ?string
    {
        return $this->CIN;
    }

    public function setCIN(string $CIN): static
    {
        $this->CIN = $CIN;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->CIN;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): static
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): static
    {
        $this->age = $age;

        return $this;
    }

    public function isSexe(): ?bool
    {
        return $this->sexe;
    }

    public function setSexe(bool $sexe): static
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function isStatusMatrimoniale(): ?bool
    {
        return $this->status_matrimoniale;
    }

    public function setStatusMatrimoniale(bool $status_matrimoniale): static
    {
        $this->status_matrimoniale = $status_matrimoniale;

        return $this;
    }

    public function isVivant(): ?bool
    {
        return $this->vivant;
    }

    public function setVivant(bool $vivant): static
    {
        $this->vivant = $vivant;

        return $this;
    }

    public function getProfession(): ?int
    {
        return $this->profession;
    }

    public function setProfession(int $profession): static
    {
        $this->profession = $profession;

        return $this;
    }

    public function getLieuNaissance(): ?string
    {
        return $this->lieu_naissance;
    }

    public function setLieuNaissance(string $lieu_naissance): static
    {
        $this->lieu_naissance = $lieu_naissance;

        return $this;
    }

    public function getPere(): ?self
    {
        return $this->pere;
    }

    public function setPere(?self $pere): static
    {
        $this->pere = $pere;

        return $this;
    }

    public function getMere(): ?self
    {
        return $this->mere;
    }

    public function setMere(?self $mere): static
    {
        $this->mere = $mere;

        return $this;
    }

    public function getPartenaire(): ?self
    {
        return $this->partenaire;
    }

    public function setPartenaire(?self $partenaire): static
    {
        $this->partenaire = $partenaire;

        return $this;
    }

    /**
     * @return Collection<int, Naissance>
     */
    public function getNaissances(): Collection
    {
        return $this->naissances;
    }

    public function addNaissance(Naissance $naissance): static
    {
        if (!$this->naissances->contains($naissance)) {
            $this->naissances->add($naissance);
            $naissance->setPere($this);
        }

        return $this;
    }

    public function removeNaissance(Naissance $naissance): static
    {
        if ($this->naissances->removeElement($naissance)) {
            // set the owning side to null (unless already changed)
            if ($naissance->getPere() === $this) {
                $naissance->setPere(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Mariage>
     */
    public function getDemandeMariage(): Collection
    {
        return $this->demande_mariage;
    }

    public function addDemandeMariage(Mariage $demandeMariage): static
    {
        if (!$this->demande_mariage->contains($demandeMariage)) {
            $this->demande_mariage->add($demandeMariage);
            $demandeMariage->setDemandeur($this);
        }

        return $this;
    }

    public function removeDemandeMariage(Mariage $demandeMariage): static
    {
        if ($this->demande_mariage->removeElement($demandeMariage)) {
            // set the owning side to null (unless already changed)
            if ($demandeMariage->getDemandeur() === $this) {
                $demandeMariage->setDemandeur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Deces>
     */
    public function getDemandeDece(): Collection
    {
        return $this->demande_dece;
    }

    public function addDemandeDece(Deces $demandeDece): static
    {
        if (!$this->demande_dece->contains($demandeDece)) {
            $this->demande_dece->add($demandeDece);
            $demandeDece->setDemandeur($this);
        }

        return $this;
    }

    public function removeDemandeDece(Deces $demandeDece): static
    {
        if ($this->demande_dece->removeElement($demandeDece)) {

src/Form/UtilisateursType.php
<?php

namespace App\Form;

use App\Entity\Porte;
use App\Entity\Profession;
use App\Entity\Utilisateurs;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RadioType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UtilisateursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('CIN')
            ->add('password', PasswordType::class)
            ->add('nom')
            ->add('prenom')
            ->add('date_naissance', null, [
                'widget' => 'single_text',
            ])
            ->add('age')
            ->add('adresse')
            ->add('sexe')
            ->add('status_matrimoniale')
            ->add('profession')
            ->add('lieu_naissance')
            ->add('pere', EntityType::class, [
                'class' => Utilisateurs::class,
                'choice_label' => 'nom',
            ])
            ->add('mere', EntityType::class, [
                'class' => Utilisateurs::class,
                'choice_label' => 'nom',
            ])
            ->add('partenaire', EntityType::class, [
                'class' => Utilisateurs::class,
                'choice_label' => 'nom',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Utilisateurs::class,
        ]);
    }
}

src/Controller/UtilisateursController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateurs;
use App\Form\UtilisateursType;
use App\Repository\UtilisateursRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/utilisateurs')]
class UtilisateursController extends AbstractController
{
    #[Route('/', name: 'app_utilisateurs_index', methods: ['GET'])]
    public function index(UtilisateursRepository $utilisateursRepository): Response
    {
        return $this->render('utilisateurs/index.html.twig', [
            'utilisateurs' => $utilisateursRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_utilisateurs_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $hasher): Response
    {
        $utilisateur = new Utilisateurs();
        $form = $this->createForm(UtilisateursType::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $mdp = $utilisateur->getPassword();
            $utilisateur->setPassword($hasher->hashPassword($utilisateur, $mdp));
            $utilisateur->setVivant(true);
            $utilisateur->setType('users');
            $entityManager->persist($utilisateur);
            $entityManager->flush();

            return $this->redirectToRoute('app_page_admin', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('utilisateurs/new.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_utilisateurs_show', methods: ['GET'])]
    public function show(Utilisateurs $utilisateur): Response
    {
        return $this->render('utilisateurs/show.html.twig', [
            'utilisateur' => $utilisateur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_utilisateurs_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Utilisateurs $utilisateur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UtilisateursType::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_utilisateurs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('utilisateurs/edit.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_utilisateurs_delete', methods: ['POST'])]
    public function delete(Request $request, Utilisateurs $utilisateur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$utilisateur->getId(), $request->request->get('_token'))) {
            $entityManager->remove($utilisateur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_utilisateurs_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/utilisateurs/_delete_form.html.twig
<form method="post" action="{{ path('app_utilisateurs_delete', {'id': utilisateur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ utilisateur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/utilisateurs/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/utilisateurs/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Utilisateurs{% endblock %}

{% block body %}
    <h1>Edit Utilisateurs</h1>

    {{ include('utilisateurs/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_utilisateurs_index') }}">back to list</a>

    {{ include('utilisateurs/_delete_form.html.twig') }}
{% endblock %}

templates/utilisateurs/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateurs index{% endblock %}

{% block body %}
    <h1>Utilisateurs index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>CIN</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Date_naissance</th>
                <th>Age</th>
                <th>Sexe</th>
                <th>Status_matrimoniale</th>
                <th>Vivant</th>
                <th>Profession</th>
                <th>Lieu_naissance</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for utilisateur in utilisateurs %}
            <tr>
                <td>{{ utilisateur.id }}</td>
                <td>{{ utilisateur.CIN }}</td>
                <td>{{ utilisateur.roles ? utilisateur.roles|json_encode : '' }}</td>
                <td>{{ utilisateur.password }}</td>
                <td>{{ utilisateur.nom }}</td>
                <td>{{ utilisateur.prenom }}</td>
                <td>{{ utilisateur.dateNaissance ? utilisateur.dateNaissance|date('Y-m-d') : '' }}</td>
                <td>{{ utilisateur.age }}</td>
                <td>{{ utilisateur.sexe ? 'Yes' : 'No' }}</td>
                <td>{{ utilisateur.statusMatrimoniale ? 'Yes' : 'No' }}</td>
                <td>{{ utilisateur.vivant ? 'Yes' : 'No' }}</td>
                <td>{{ utilisateur.profession }}</td>
                <td>{{ utilisateur.lieuNaissance }}</td>
                <td>
                    <a href="{{ path('app_utilisateurs_show', {'id': utilisateur.id}) }}">show</a>
                    <a href="{{ path('app_utilisateurs_edit', {'id': utilisateur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_utilisateurs_new') }}">Create new</a>
{% endblock %}

templates/utilisateurs/new.html.twig
{% extends 'ajout_user.html.twig' %}

{% block title %}New Utilisateurs{% endblock %}

{% block body %}

    {{ include('utilisateurs/_form.html.twig') }}

    <a href="{{ path('app_utilisateurs_index') }}">back to list</a>
{% endblock %}

templates/utilisateurs/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateurs{% endblock %}

{% block body %}
    <h1>Utilisateurs</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ utilisateur.id }}</td>
            </tr>
            <tr>
                <th>CIN</th>
                <td>{{ utilisateur.CIN }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ utilisateur.roles ? utilisateur.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ utilisateur.password }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ utilisateur.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ utilisateur.prenom }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ utilisateur.dateNaissance ? utilisateur.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ utilisateur.age }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ utilisateur.sexe ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Status_matrimoniale</th>
                <td>{{ utilisateur.statusMatrimoniale ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Vivant</th>
                <td>{{ utilisateur.vivant ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Profession</th>
                <td>{{ utilisateur.profession }}</td>
            </tr>
            <tr>
                <th>Lieu_naissance</th>
                <td>{{ utilisateur.lieuNaissance }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_utilisateurs_index') }}">back to list</a>

    <a href="{{ path('app_utilisateurs_edit', {'id': utilisateur.id}) }}">edit</a>

    {{ include('utilisateurs/_delete_form.html.twig') }}
{% endblock %}