src/Entity/Deces.php
<?php

namespace App\Entity;

use App\Repository\DecesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DecesRepository::class)]
class Deces
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_dece = null;

    #[ORM\Column(length: 255)]
    private ?string $cin = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Utilisateurs $utilisateur = null;

    #[ORM\ManyToOne(inversedBy: 'demande_dece')]
    private ?Utilisateurs $demandeur = null;

    #[ORM\Column(length: 255, nullable:true)]
    private ?string $fichier_retour = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable:true)]
    private ?\DateTimeInterface $dateDemande = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateRetour = null;

    #[ORM\Column]
    private ?bool $confirmation = null;

    #[ORM\Column]
    private ?int $num_porte = null;

    #[ORM\ManyToOne(inversedBy: 'demandeur_acte')]
    private ?Utilisateurs $demandeur_acte = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateDece(): ?\DateTimeInterface
    {
        return $this->date_dece;
    }

    public function setDateDece(\DateTimeInterface $date_dece): static
    {
        $this->date_dece = $date_dece;

        return $this;
    }

    public function getCin(): ?string
    {
        return $this->cin;
    }

    public function setCin(string $cin): static
    {
        $this->cin = $cin;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateurs
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateurs $utilisateur): static
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getDemandeur(): ?Utilisateurs
    {
        return $this->demandeur;
    }

    public function setDemandeur(?Utilisateurs $demandeur): static
    {
        $this->demandeur = $demandeur;

        return $this;
    }

    public function getFichierRetour(): ?string
    {
        return $this->fichier_retour;
    }

    public function setFichierRetour(string $fichier_retour): static
    {
        $this->fichier_retour = $fichier_retour;

        return $this;
    }

    public function getDateDemande(): ?\DateTimeInterface
    {
        return $this->dateDemande;
    }

    public function setDateDemande(\DateTimeInterface $dateDemande): static
    {
        $this->dateDemande = $dateDemande;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->dateRetour;
    }

    public function setDateRetour(?\DateTimeInterface $dateRetour): static
    {
        $this->dateRetour = $dateRetour;

        return $this;
    }

    public function isConfirmation(): ?bool
    {
        return $this->confirmation;
    }

    public function setConfirmation(bool $confirmation): static
    {
        $this->confirmation = $confirmation;

        return $this;
    }

    public function getNumPorte(): ?int
    {
        return $this->num_porte;
    }

    public function setNumPorte(int $num_porte): static
    {
        $this->num_porte = $num_porte;

        return $this;
    }

    public function getDemandeurActe(): ?Utilisateurs
    {
        return $this->demandeur_acte;
    }

    public function setDemandeurActe(?Utilisateurs $demandeur_acte): static
    {
        $this->demandeur_acte = $demandeur_acte;

        return $this;
    }
}

src/Form/DecesType.php
<?php

namespace App\Form;

use App\Entity\Deces;
use App\Entity\Utilisateurs;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DecesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('date_dece', null, [
                'widget' => 'single_text',
            ])
            ->add('cin')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Deces::class,
        ]);
    }
}

src/Controller/DecesController.php
<?php

namespace App\Controller;

use App\Entity\Deces;
use App\Form\DecesType;
use App\Repository\DecesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/deces')]
class DecesController extends AbstractController
{
    #[Route('/', name: 'app_deces_index', methods: ['GET'])]
    public function index(DecesRepository $decesRepository): Response
    {
        return $this->render('deces/index.html.twig', [
            'deces' => $decesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_deces_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $dece = new Deces();
        $form = $this->createForm(DecesType::class, $dece);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $dece->setConfirmation(false);
            $dece->setDemandeur($this->getUser());
            $dece->setNumPorte(23);
            $entityManager->persist($dece);
            $entityManager->flush();

            return $this->redirectToRoute('app_recup_fichier', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('deces/new.html.twig', [
            'dece' => $dece,
            'form' => $form,
        ]);
    }
    #[Route('/new/acte', name: 'app_deces_acte_new', methods: ['GET', 'POST'])]
    public function newacte(Request $request, EntityManagerInterface $entityManager): Response
    {
        $dece = new Deces();
        $form = $this->createForm(DecesType::class, $dece);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $dece->setConfirmation(false);
            $dece->setDemandeurActe($this->getUser());
            $dece->setNumPorte(23);
            $entityManager->persist($dece);
            $entityManager->flush();

            return $this->redirectToRoute('app_recup_fichier', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('deces/new.html.twig', [
            'dece' => $dece,
            'form' => $form,
        ]);
    }
    #[Route('/{id}', name: 'app_deces_show', methods: ['GET'])]
    public function show(Deces $dece): Response
    {
        return $this->render('deces/show.html.twig', [
            'dece' => $dece,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_deces_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Deces $dece, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DecesType::class, $dece);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_deces_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('deces/edit.html.twig', [
            'dece' => $dece,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_deces_delete', methods: ['POST'])]
    public function delete(Request $request, Deces $dece, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$dece->getId(), $request->request->get('_token'))) {
            $entityManager->remove($dece);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_deces_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/deces/_delete_form.html.twig
<form method="post" action="{{ path('app_deces_delete', {'id': dece.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ dece.id) }}">
    <button class="btn">Delete</button>
</form>

templates/deces/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/deces/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Deces{% endblock %}

{% block body %}
    <h1>Edit Deces</h1>

    {{ include('deces/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_deces_index') }}">back to list</a>

    {{ include('deces/_delete_form.html.twig') }}
{% endblock %}

templates/deces/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Deces index{% endblock %}

{% block body %}
    <h1>Deces index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Date_dece</th>
                <th>Cin</th>
                <th>Fichier_retour</th>
                <th>DateDemande</th>
                <th>DateRetour</th>
                <th>Confirmation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for dece in deces %}
            <tr>
                <td>{{ dece.id }}</td>
                <td>{{ dece.nom }}</td>
                <td>{{ dece.prenom }}</td>
                <td>{{ dece.dateDece ? dece.dateDece|date('Y-m-d') : '' }}</td>
                <td>{{ dece.cin }}</td>
                <td>{{ dece.fichierRetour }}</td>
                <td>{{ dece.dateDemande ? dece.dateDemande|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ dece.dateRetour ? dece.dateRetour|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ dece.confirmation ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_deces_show', {'id': dece.id}) }}">show</a>
                    <a href="{{ path('app_deces_edit', {'id': dece.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_deces_new') }}">Create new</a>
{% endblock %}

templates/deces/new.html.twig
{% extends 'demande_user.html.twig' %}

{% block demande %}Déclaration de décè{% endblock %}

{% block body %}
    {{ include('deces/_form.html.twig') }}
{% endblock %}

templates/deces/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Deces{% endblock %}

{% block body %}
    <h1>Deces</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ dece.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ dece.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ dece.prenom }}</td>
            </tr>
            <tr>
                <th>Date_dece</th>
                <td>{{ dece.dateDece ? dece.dateDece|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Cin</th>
                <td>{{ dece.cin }}</td>
            </tr>
            <tr>
                <th>Fichier_retour</th>
                <td>{{ dece.fichierRetour }}</td>
            </tr>
            <tr>
                <th>DateDemande</th>
                <td>{{ dece.dateDemande ? dece.dateDemande|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>DateRetour</th>
                <td>{{ dece.dateRetour ? dece.dateRetour|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Confirmation</th>
                <td>{{ dece.confirmation ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_deces_index') }}">back to list</a>

    <a href="{{ path('app_deces_edit', {'id': dece.id}) }}">edit</a>

    {{ include('deces/_delete_form.html.twig') }}
{% endblock %}